"""email verification

Revision ID: 0babaeb837c4
Revises: cb65e3b119d5
Create Date: 2026-10-08 15:45:30.941378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0babaeb837c4'
down_revision: Union[str, None] = 'cb65e3b119d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('users', 'email_verified', server_default=None)
    op.add_column('users', sa.Column('verification_code_hash', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('verification_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_expires_at')
    op.drop_column('users', 'verification_code_hash')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
