"""ratings

Revision ID: 3c7b6bae671c
Revises: f03cd1e6bd2a
Create Date: 2026-10-07 23:52:18.653874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c7b6bae671c'
down_revision: Union[str, None] = 'f03cd1e6bd2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('handover_id', sa.UUID(), nullable=False),
    sa.Column('from_user_id', sa.UUID(), nullable=False),
    sa.Column('to_user_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['handover_id'], ['handovers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('handover_id', 'from_user_id', name='uq_rating_handover_from')
    )
    op.create_index(op.f('ix_ratings_from_user_id'), 'ratings', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_ratings_handover_id'), 'ratings', ['handover_id'], unique=False)
    op.create_index(op.f('ix_ratings_to_user_id'), 'ratings', ['to_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ratings_to_user_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_handover_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_from_user_id'), table_name='ratings')
    op.drop_table('ratings')
    # ### end Alembic commands ###
