"""handovers

Revision ID: dfd3f3ba91a9
Revises: 09799498cd31
Create Date: 2026-10-07 22:33:13.443887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfd3f3ba91a9'
down_revision: Union[str, None] = '09799498cd31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('handovers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('seller_token', sa.String(length=12), nullable=False),
    sa.Column('buyer_token', sa.String(length=12), nullable=False),
    sa.Column('seller_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('buyer_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('receipt_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_handovers_offer_id'), 'handovers', ['offer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_handovers_offer_id'), table_name='handovers')
    op.drop_table('handovers')
    # ### end Alembic commands ###
