"""wanted posts and bids

Revision ID: f03cd1e6bd2a
Revises: dfd3f3ba91a9
Create Date: 2026-10-07 22:45:15.132590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f03cd1e6bd2a'
down_revision: Union[str, None] = 'dfd3f3ba91a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wanted_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('max_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('min_condition', sa.String(length=20), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wanted_posts_buyer_id'), 'wanted_posts', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_wanted_posts_status'), 'wanted_posts', ['status'], unique=False)
    op.create_table('wanted_bids',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wanted_post_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('bid_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wanted_post_id'], ['wanted_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wanted_bids_seller_id'), 'wanted_bids', ['seller_id'], unique=False)
    op.create_index(op.f('ix_wanted_bids_status'), 'wanted_bids', ['status'], unique=False)
    op.create_index(op.f('ix_wanted_bids_wanted_post_id'), 'wanted_bids', ['wanted_post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wanted_bids_wanted_post_id'), table_name='wanted_bids')
    op.drop_index(op.f('ix_wanted_bids_status'), table_name='wanted_bids')
    op.drop_index(op.f('ix_wanted_bids_seller_id'), table_name='wanted_bids')
    op.drop_table('wanted_bids')
    op.drop_index(op.f('ix_wanted_posts_status'), table_name='wanted_posts')
    op.drop_index(op.f('ix_wanted_posts_buyer_id'), table_name='wanted_posts')
    op.drop_table('wanted_posts')
    # ### end Alembic commands ###
